const products = [
    {
        id:1,
        title:"Saint-Seiya: Shura",
        description:"Stock disponible",
        price:"45",
        categoria:"1",
        pictureUrl:"saint-seiya-shura.webp",
        pictureUrl1:"saint-seiya-shura.1.webp",
        pictureUrl2:"saint-seiya-shura.2.webp",
        pictureUrl3:"saint-seiya-shura.3.webp",
        pictureUrl4:"saint-seiya-shura.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:2,
        title:"Saint-Seiya: Shaka",
        description:"Stock disponible",
        price:"50",
        categoria:"1",
        pictureUrl:"saint-seiya-shaka.webp",
        pictureUrl1:"saint-seiya-shaka.1.webp",
        pictureUrl2:"saint-seiya-shaka.2.webp",
        pictureUrl3:"saint-seiya-shaka.3.webp",
        pictureUrl4:"saint-seiya-shaka.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:3,
        title:"Saint-Seiya: Aldebaran",
        description:"Stock disponible",
        price:"35",
        categoria:"1",
        pictureUrl:"saint-seiya-aldebaran.webp",
        pictureUrl1:"saint-seiya-aldebaran.1.webp",
        pictureUrl2:"saint-seiya-aldebaran.2.webp",
        pictureUrl3:"saint-seiya-aldebaran.3.webp",
        pictureUrl4:"saint-seiya-aldebaran.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:4,
        title:"Saint-Seiya: Milo",
        description:"Stock disponible",
        price:"42",
        categoria:"1",
        pictureUrl:"saint-seiya-milo.webp",
        pictureUrl1:"saint-seiya-milo.1.webp",
        pictureUrl2:"saint-seiya-milo.2.webp",
        pictureUrl3:"saint-seiya-milo.3.webp",
        pictureUrl4:"saint-seiya-milo.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:5,
        title:"Saint-Seiya: Aioria",
        description:"Stock disponible",
        price:"40",
        categoria:"1",
        pictureUrl:"saint-seiya-aioria.webp",
        pictureUrl1:"saint-seiya-aioria.1.webp",
        pictureUrl2:"saint-seiya-aioria.2.webp",
        pictureUrl3:"saint-seiya-aioria.3.webp",
        pictureUrl4:"saint-seiya-aioria.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:6,
        title:"Dragon Ball: Goku SSJ2",
        description:"Stock disponible",
        price:"38",
        categoria:"2",
        pictureUrl:"dragon-ball-goku.webp",
        pictureUrl1:"dragon-ball-goku.1.webp",
        pictureUrl2:"dragon-ball-goku.2.webp",
        pictureUrl3:"dragon-ball-goku.3.webp",
        pictureUrl4:"dragon-ball-goku.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:7,
        title:"Dragon Ball: Broly",
        description:"Stock disponible",
        price:"48",
        categoria:"2",
        pictureUrl:"dragon-ball-broly.webp",
        pictureUrl1:"dragon-ball-broly.1.webp",
        pictureUrl2:"dragon-ball-broly.2.webp",
        pictureUrl3:"dragon-ball-broly.3.webp",
        pictureUrl4:"dragon-ball-broly.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:8,
        title:"Dragon Ball: Trunks SSJ",
        description:"Stock disponible",
        price:"45",
        categoria:"2",
        pictureUrl:"dragon-ball-trunks.webp",
        pictureUrl1:"dragon-ball-trunks.1.webp",
        pictureUrl2:"dragon-ball-trunks.2.webp",
        pictureUrl3:"dragon-ball-trunks.3.webp",
        pictureUrl4:"dragon-ball-trunks.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:9,
        title:"One Piece: Monkey D.Luffy",
        description:"Stock disponible",
        price:"35",
        categoria:"3",
        pictureUrl:"one-piece-luffy.jpg",
        pictureUrl1:"one-piece-luffy.1.webp",
        pictureUrl2:"one-piece-luffy.2.jpg",
        pictureUrl3:"one-piece-luffy.3.jpg",
        pictureUrl4:"one-piece-luffy.4.jpg",
        stock: 10,
        initial: 0
    },
    {
        id:10,
        title:"One Piece: Roronoa Zoro",
        description:"Stock disponible",
        price:"38",
        categoria:"3",
        pictureUrl:"one-piece-zoro.webp",
        pictureUrl1:"one-piece-zoro.1.webp",
        pictureUrl2:"one-piece-zoro.2.webp",
        pictureUrl3:"one-piece-zoro.3.webp",
        pictureUrl4:"one-piece-zoro.4.webp",
        stock: 10,
        initial: 0
    },
    {
        id:11,
        title:"One Piece: Portgas D.Ace",
        description:"Stock disponible",
        price:"50",
        categoria:"3",
        pictureUrl:"one-piece-ace.webp",
        pictureUrl1:"one-piece-ace.1.webp",
        pictureUrl2:"one-piece-ace.2.webp",
        pictureUrl3:"one-piece-ace.3.webp",
        pictureUrl4:"one-piece-ace.4.webp",
        stock: 10,
        initial: 0
    }
]

export default products;